"""Orchestrator: run the full immrep25 audit and write results/ + appendix .dat tables.

Methodology: one-vs-many per epitope (each epitope with >= MIN_N records scored
against all others), aggregated to a dataset geometric mean +/- 95% CI across
epitopes -- no bootstrap resampling. Two OLGA controls (random + pgen-matched)
anchor the noise floor.

Usage: python run_audit.py
"""
from __future__ import annotations
import os, sys
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))
from cohorts import build_cohorts, HIERARCHY, COHORT_META, counts_table
from homology import per_epitope_sn, dataset_sn
from homology_graph import build_graph, graph_stats, graph_subsets
from pairing import pairing_per_epitope, dataset_pairing
from publicity import annotate_publicity
from load_data import load_vdjdb, _pair_to_long
from epitope_hla import EPITOPE_HLA        # epitope -> restricting HLA (generated from data)
import audit_stats as astat

REPO = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(REPO, "results"); os.makedirs(RESULTS, exist_ok=True)
ADAT = os.path.join(REPO, "appendix", "analysis"); os.makedirs(ADAT, exist_ok=True)
TABLES = os.path.join(os.path.dirname(REPO), "2026-immrep25-audit-ms", "tables")

MIN_N = 30       # minimum records per epitope for one-vs-many
MAX_D = 3
COLIDX = {n: i for i, n in enumerate(HIERARCHY)}


def _gen_header(script: str) -> str:
    """Provenance stamp for a generated table -- never hand-edit these files."""
    return ("%% GENERATED by %s -- do not edit.\n"
            "%% Regenerate: python %s (from the 2026-immrep25-audit repo).\n" % (script, script))


def _write_dat(df: pd.DataFrame, name: str):
    # na_rep is load-bearing: an empty field would be swallowed by gnuplot's whitespace
    # collapsing and shift every later column left (MLR is beta-only, so TRA has a gap).
    with open(os.path.join(ADAT, name), "w") as fh:
        fh.write("# " + " ".join(df.columns) + "\n")
        df.to_csv(fh, sep=" ", index=False, header=False, na_rep="NaN")


def _swarm(y, binwidth=0.18, dx=0.035, maxw=0.34):
    """Beeswarm x-offsets: bin points by y and spread each bin symmetrically (no y-jitter)."""
    from collections import defaultdict
    y = np.asarray(y, float)
    off = np.zeros(len(y))
    groups = defaultdict(list)
    for i in np.argsort(y):
        groups[int(round(y[i] / binwidth))].append(i)
    for idxs in groups.values():
        k = len(idxs)
        pos = np.clip((np.arange(k) - (k - 1) / 2.0) * dx, -maxw, maxw)
        for i, p in zip(idxs, pos):
            off[i] = p
    return off


def run():
    coh = build_cohorts(include_olga=True)
    order = [c for c in HIERARCHY if c in coh]
    rng = np.random.default_rng(0)

    ct = counts_table(coh); ct.to_csv(os.path.join(RESULTS, "counts.csv"), index=False)
    print(ct.to_string(index=False)); print()

    # ---------------- homology (one-vs-many, per chain, d=1..3) ----------------
    hom_rows, per_ep = [], {}
    for name in order:
        for chain in ("A", "B"):
            lc = coh[name]["long"]; lc = lc[lc.chain == chain]
            pe = per_epitope_sn(lc, max_d=MAX_D, min_n=MIN_N, seed=1)
            per_ep[(name, chain)] = pe
            for d in range(1, MAX_D + 1):
                s = dataset_sn(pe, d)
                hom_rows.append({"cohort": name, "label": COHORT_META[name]["label"],
                                 "chain": chain, "d": d, **s})
    hom = pd.DataFrame(hom_rows)
    hom.to_csv(os.path.join(RESULTS, "homology_sn.csv"), index=False)
    # per-epitope d=1 S/N (one row per epitope) -> ANOVA / Tukey / grand-median stars
    hpe = pd.DataFrame(
        [{"cohort": name, "chain": chain, "epitope": r.epitope, "n": int(r.n), "sn1": float(r.sn1)}
         for (name, chain), pe in per_ep.items() for _, r in pe.iterrows()])
    hpe.to_csv(os.path.join(RESULTS, "homology_per_epitope.csv"), index=False)
    for chain in ("A", "B"):
        d1 = hom[(hom.chain == chain) & (hom.d == 1)].set_index("cohort").loc[order].reset_index()
        d1 = d1.assign(x=[COLIDX[c] for c in d1.cohort])[["x", "cohort", "sn", "lo", "hi"]]
        _write_dat(d1, f"homology_d1_TR{chain}.dat")
        # d-lines: rows = d, one column per cohort
        wide = {"d": list(range(1, MAX_D + 1))}
        for name in order:
            sub = hom[(hom.cohort == name) & (hom.chain == chain)].sort_values("d")
            wide[name] = sub.sn.values
        _write_dat(pd.DataFrame(wide), f"homology_dlines_TR{chain}.dat")
    print("[homology one-vs-many d1 S/N]")
    print(hom[hom.d == 1][["cohort", "chain", "sn", "lo", "hi", "n_ep"]].to_string(index=False)); print()

    # beeswarm, per chain: per-epitope rate points, their median, and the non-self reference
    for chain in ("A", "B"):
        bee, ref = [], []
        for name in order:
            pe = per_ep.get((name, chain))
            pe = pe if pe is not None else pd.DataFrame(columns=["r_self", "r_nonself"])
            rates = np.maximum(pe.r_self.values, 1e-4) if len(pe) else np.array([])
            xoff = _swarm(np.log10(rates)) if len(rates) else []
            for rate, o in zip(rates, xoff):
                bee.append({"x": COLIDX[name] + o, "rate": rate})
            # reference bar: geometric mean of the per-epitope non-self rates, matching how
            # every other cohort-level number in the audit is aggregated (never pooled counts)
            rn = pe.r_nonself.values[np.isfinite(pe.r_nonself.values) & (pe.r_nonself.values > 0)] if len(pe) else []
            rn = 10 ** np.log10(rn).mean() if len(rn) else np.nan
            # median of the points themselves, drawn as the cohort's central line in the panel
            med = float(np.median(rates)) if len(rates) else np.nan
            ref.append({"x": COLIDX[name], "r_nonself": max(rn, 1e-4) if rn == rn else 1e-4,
                        "median": med if med == med else 1e-4})
        _write_dat(pd.DataFrame(bee, columns=["x", "rate"]), f"homology_beeswarm_TR{chain}.dat")
        _write_dat(pd.DataFrame(ref)[["x", "r_nonself", "median"]],
                   f"homology_beeswarm_ref_TR{chain}.dat")

    # an epitope can qualify on one chain and not the other, so the per-chain cells print "--"
    # rather than a value derived from too few records
    def _int(v):
        return "--" if v is None or pd.isna(v) else "%d" % int(v)

    def _num(v):
        return "--" if v is None or pd.isna(v) else "%.2f" % v

    # immrep25 by-epitope table (within-epitope Hamming<=1 neighbours and S/N per chain)
    peB = per_ep[("immrep25_pos", "B")][["epitope", "n", "m1", "sn1"]].rename(columns={"m1": "mB", "sn1": "snB"})
    peA = per_ep[("immrep25_pos", "A")][["epitope", "m1", "sn1"]].rename(columns={"m1": "mA", "sn1": "snA"})
    imm_tab = peB.merge(peA, on="epitope", how="left").sort_values("snB", ascending=False)
    def _srow(cohort):
        peb, pea = per_ep[(cohort, "B")], per_ep[(cohort, "A")]
        pr = coh[cohort]["paired"]
        n = len(pr) if pr is not None else int((coh[cohort]["long"].chain == "B").sum())
        # both chains' S/N: the geometric mean over that chain's qualifying epitopes
        return (n, int(peb.m1.sum()), int(pea.m1.sum()), dataset_sn(peb, 1)["sn"],
                dataset_sn(pea, 1)["sn"] if len(pea) else float("nan"))
    with open(os.path.join(TABLES, "immrep_epitope_table.tex"), "w") as fh:
        fh.write(_gen_header("run_audit.py"))
        fh.write("\\begin{tabular}{llrrrrr}\n\\toprule\n")
        fh.write("epitope & HLA & $n$ & $\\beta$ nbrs & $\\beta$ S/N & $\\alpha$ nbrs"
                 " & $\\alpha$ S/N \\\\\n\\midrule\n")
        for _, r in imm_tab.iterrows():
            fh.write("\\texttt{%s} & \\texttt{%s} & %d & %d & %.2f & %s & %s \\\\\n"
                     % (r.epitope, EPITOPE_HLA.get(r.epitope, ""), r.n, r.mB, r.snB,
                        _int(r.mA), _num(r.snA)))
        fh.write("\\midrule\n")
        summary = [("\\textbf{IMMREP25$^{(+)}$ (geom.\\ mean)}", "immrep25_pos"),
                   ("IMMREP22$^{(+)}$ (geom.\\ mean)", "immrep22_true"),
                   ("pairSEQ mock", "pairseq_mock"),
                   ("MLR expanded ($\\beta$ only)", "mlr_prolif")]
        for label, cohort in summary:
            if cohort not in coh:
                continue
            n, mb, ma, snb, sna = _srow(cohort)
            beta_only = coh[cohort]["paired"] is None
            fh.write("%s & & %s & %d & %.2f & %s & %s \\\\\n"
                     % (label, "{:,}".format(n), mb, snb, "--" if beta_only else _int(ma),
                        "--" if beta_only else _num(sna)))
        fh.write("\\bottomrule\n\\end{tabular}\n")
    om = _srow("olga_random")
    imm_within = (int(imm_tab.mB.sum()), int(imm_tab.mA.sum()), om[1], om[2])

    # immrep22 by-epitope table (Table S2): seen-benchmark per-epitope detail, parity with immrep25
    i2B = per_ep[("immrep22_true", "B")][["epitope", "n", "m1", "sn1"]].rename(columns={"m1": "mB", "sn1": "snB"})
    i2A = per_ep[("immrep22_true", "A")][["epitope", "m1", "sn1"]].rename(columns={"m1": "mA", "sn1": "snA"})
    i2_tab = i2B.merge(i2A, on="epitope", how="left").sort_values("snB", ascending=False)
    with open(os.path.join(TABLES, "immrep22_epitope_table.tex"), "w") as fh:
        fh.write(_gen_header("run_audit.py"))
        fh.write("\\begin{tabular}{llrrrrr}\n\\toprule\n")
        fh.write("epitope & HLA & $n$ & $\\beta$ nbrs & $\\beta$ S/N & $\\alpha$ nbrs"
                 " & $\\alpha$ S/N \\\\\n\\midrule\n")
        for _, r in i2_tab.iterrows():
            fh.write("\\texttt{%s} & \\texttt{%s} & %d & %d & %.2f & %s & %s \\\\\n"
                     % (r.epitope, EPITOPE_HLA.get(r.epitope, ""), int(r.n), int(r.mB), r.snB,
                        _int(r.mA), _num(r.snA)))
        fh.write("\\midrule\n")
        n22, mb22, ma22, snb22, sna22 = _srow("immrep22_true")
        fh.write("\\textbf{IMMREP22 (geom.\\ mean)} & & %s & %d & %.2f & %d & %.2f \\\\\n"
                 % ("{:,}".format(n22), mb22, snb22, ma22, sna22))
        fh.write("\\bottomrule\n\\end{tabular}\n")

    # ---------------- pairing (one-vs-many, excess bits) ----------------
    pair_rows, pair_pe = [], []
    for name in order:
        if coh[name]["paired"] is None:
            continue
        pe = pairing_per_epitope(coh[name]["paired"], min_n=MIN_N, n_null=40, seed=1)
        pair_pe.append(pe.assign(cohort=name)[["cohort", "epitope", "n", "gene_excess",
                                               "gene_excess_a", "gene_excess_b", "mi_excess"]])
        g = dataset_pairing(pe, "gene_excess"); m = dataset_pairing(pe, "mi_excess")
        ga = dataset_pairing(pe, "gene_excess_a"); gb = dataset_pairing(pe, "gene_excess_b")
        pair_rows.append({"cohort": name, "label": COHORT_META[name]["label"], "n_ep": g["n_ep"],
                          "gene_mean": g["mean"], "gene_lo": g["lo"], "gene_hi": g["hi"],
                          "geneA_mean": ga["mean"], "geneA_lo": ga["lo"], "geneA_hi": ga["hi"],
                          "geneB_mean": gb["mean"], "geneB_lo": gb["lo"], "geneB_hi": gb["hi"],
                          "mi_mean": m["mean"], "mi_lo": m["lo"], "mi_hi": m["hi"]})
    pair = pd.DataFrame(pair_rows)
    pair.to_csv(os.path.join(RESULTS, "pairing.csv"), index=False)
    ppe = pd.concat(pair_pe, ignore_index=True) if pair_pe else pd.DataFrame(
        columns=["cohort", "epitope", "n", "gene_excess", "gene_excess_a", "gene_excess_b",
                 "mi_excess"])
    ppe.to_csv(os.path.join(RESULTS, "pairing_per_epitope.csv"), index=False)
    pg = pair.assign(x=[COLIDX[c] for c in pair.cohort])[
        ["x", "cohort", "geneA_mean", "geneA_lo", "geneA_hi", "geneB_mean", "geneB_lo", "geneB_hi",
         "mi_mean", "mi_lo", "mi_hi"]]
    _write_dat(pg, "pairing_excess.dat")
    print("[pairing one-vs-many, excess bits]"); print(pair.to_string(index=False)); print()

    # ---------------- graph stats (chain B, epitopes >= MIN_N records) ----------------
    # Oversized cohorts (VDJdb LQ ~135k) are subsampled to the largest feasible cohort's
    # size via graph_subsets (same helper the figure uses -> graph N matches the panel).
    grows = []
    graphed = [c for c in order if c not in ("mlr_prolif", "airr_control")]  # MLR beta-only; AIRR random dropped
    gsub = graph_subsets(coh, graphed, chain="B", min_n=MIN_N)
    for name in graphed:
        sub, full_n, n_eps = gsub[name]
        st = graph_stats(build_graph(sub)); st["cohort"] = name; st["label"] = COHORT_META[name]["label"]
        st["n_epitopes"] = n_eps; st["n_full"] = full_n; grows.append(st)
    gdf = pd.DataFrame(grows); gdf.to_csv(os.path.join(RESULTS, "graph_stats.csv"), index=False)
    print("[graph stats chain B, all epitopes >=%d]" % MIN_N); print(gdf.to_string(index=False)); print()

    # ---------------- publicity ----------------
    imm = coh["immrep25_pos"]["paired"]
    vlong, _ = load_vdjdb()
    ann = annotate_publicity(imm, vlong, [coh["tcrvdb_true"]["paired"], coh["tcrvdb_false"]["paired"]])
    prows = []
    # non-public subset is small (~12 TCRs/epitope) so use a lower per-epitope floor
    # for BOTH subsets here -- a fair within-immrep with/without-public contrast.
    for label, sub in [("all", ann), ("non_public", ann[~ann.public_any])]:
        lg = _pair_to_long(sub)
        for chain in ("A", "B"):
            pe = per_epitope_sn(lg[lg.chain == chain], max_d=MAX_D, min_n=10, seed=1)
            s = dataset_sn(pe, 1)
            # raw within-epitope neighbour-pair count: for the novel subset this is the honest
            # statistic, since with 0 pairs everywhere the pseudocount pins S/N at exactly 1
            # and its CI collapses to zero width.
            prows.append({"subset": label, "chain": chain, "n": len(sub),
                          "n_ep": int(len(pe)), "within_pairs": int(pe.m1.sum()),
                          "sn": s["sn"], "lo": s["lo"], "hi": s["hi"]})
    pub = pd.DataFrame(prows)
    # Same publicity contrast on the INTER-CHAIN probe: if IMMREP25's residual V/J coupling is
    # publicity (as its residual homology is), it should vanish with the public receptors. Scored
    # at the same per-epitope floor of 10 and against the pairSEQ mock for reference.
    mi_rows = []
    for label, sub in [("all", ann), ("non_public", ann[~ann.public_any]),
                       ("pairseq_mock", coh["pairseq_mock"]["paired"])]:
        pe = pairing_per_epitope(sub, min_n=10, n_null=200, seed=1)
        v = pe.mi_excess.to_numpy()
        se = float(v.std(ddof=1) / np.sqrt(len(v))) if len(v) > 1 else np.nan
        mi_rows.append({"subset": label, "n": len(sub), "n_ep": len(v),
                        "mi_excess": float(v.mean()),
                        "lo": float(v.mean() - 1.96 * se), "hi": float(v.mean() + 1.96 * se)})
    pub_mi = pd.DataFrame(mi_rows)
    pub_mi.to_csv(os.path.join(RESULTS, "publicity_pairing.csv"), index=False)
    print("[publicity inter-chain MI, floor 10]"); print(pub_mi.to_string(index=False))
    pub_summary = pd.DataFrame([{"frac_public_a": ann.public_a.mean(), "frac_public_b": ann.public_b.mean(),
                                 "frac_public_any": ann.public_any.mean(),
                                 "frac_public_both": (ann.public_a & ann.public_b).mean()}])
    pub.to_csv(os.path.join(RESULTS, "publicity.csv"), index=False)
    pub_summary.to_csv(os.path.join(RESULTS, "publicity_fractions.csv"), index=False)
    _write_dat(pub.assign(x=range(len(pub)))[["x", "subset", "chain", "sn", "lo", "hi"]], "publicity.dat")
    print("[publicity fractions]"); print(pub_summary.to_string(index=False))
    print("[publicity homology d1 S/N]"); print(pub.to_string(index=False))

    # pgen distributions for the pgen figure
    cache = os.path.join(REPO, "cache", "immrep_pgen.npz")
    if os.path.exists(cache):
        d = np.load(cache)
        for arr, nm in [(d["pa"], "pgen_immrep_A.dat"), (d["pb"], "pgen_immrep_B.dat")]:
            _write_dat(pd.DataFrame({"log10pgen": np.log10(arr[arr > 0])}), nm)
        for ch in ("A", "B"):
            pool = pd.read_csv(os.path.join(REPO, "cache", "olga_pool_%s.tsv" % ch), sep="\t",
                               names=["cdr3", "v", "j", "pgen"])
            pool = pool[pool.pgen > 0].sample(min(20000, len(pool)), random_state=0)
            _write_dat(pd.DataFrame({"log10pgen": np.log10(pool.pgen)}), "pgen_olga_%s.dat" % ch)
            # real-repertoire reference on the same axis; point pgen is already cached
            # alongside the 1-mismatch neighbourhood sums computed by src/compute_1mm.py
            ap = os.path.join(REPO, "cache", "pgen1mm_airr_control_%s.tsv" % ch)
            if os.path.exists(ap):
                a = pd.read_csv(ap, sep="\t")
                a = a[a.pgen > 0]
                _write_dat(pd.DataFrame({"log10pgen": np.log10(a.pgen)}), "pgen_airr_%s.dat" % ch)

    # ---------------- LaTeX macros ----------------
    def H(cohort, chain, d=1):
        r = hom[(hom.cohort == cohort) & (hom.chain == chain) & (hom.d == d)]
        return float(r.sn.iloc[0]) if len(r) else float("nan")

    def HC(cohort, chain, bound, d=1):     # homology CI bound
        r = hom[(hom.cohort == cohort) & (hom.chain == chain) & (hom.d == d)]
        return float(r[bound].iloc[0]) if len(r) else float("nan")

    def P(cohort, col):
        r = pair[pair.cohort == cohort]
        return float(r[col].iloc[0]) if len(r) else float("nan")

    def PM(subset, col):                   # publicity-split inter-chain MI
        r = pub_mi[pub_mi.subset == subset]
        return float(r[col].iloc[0]) if len(r) else float("nan")
    def GW(cohort):  # graph within-epitope edge fraction, as a percentage
        r = gdf[gdf.cohort == cohort]
        return 100 * float(r.within_frac.iloc[0]) if len(r) and pd.notna(r.within_frac.iloc[0]) else float("nan")

    def NEP(cohort, chain="B"):  # number of qualifying epitopes (>= MIN_N records)
        r = hom[(hom.cohort == cohort) & (hom.chain == chain) & (hom.d == 1)]
        return int(r.n_ep.iloc[0]) if len(r) else 0

    # ---- significance layer: ANOVA + Tukey post-hoc, stars = differs from IMMREP25 ----
    # Displayed cohorts (the bar set): homology beta 0-7 (incl. MLR), alpha 0-6 (no MLR);
    # pairing 0-6 (no MLR; AIRR-random/OLGA dropped from the panels).
    DISP_HOM = {"B": ["tcrvdb_true", "vdjdb_hq", "immrep22_true", "vdjdb_lq", "tcrvdb_false",
                      "immrep25_pos", "pairseq_mock", "mlr_prolif"],
                "A": ["tcrvdb_true", "vdjdb_hq", "immrep22_true", "vdjdb_lq", "tcrvdb_false",
                      "immrep25_pos", "pairseq_mock"]}
    # The pairSEQ mock is scored on the same 20 well labels as IMMREP25's 20 epitopes, so it
    # belongs on the pairing panel too: it is the platform-matched floor the benchmark is read
    # against, on all three series.
    DISP_PAIR = ["tcrvdb_true", "vdjdb_hq", "immrep22_true", "vdjdb_lq", "tcrvdb_false",
                 "immrep25_pos", "pairseq_mock"]
    sig = {}
    for chain in ("B", "A"):
        disp = [c for c in DISP_HOM[chain] if c in order]
        groups = [np.log10(hpe[(hpe.cohort == c) & (hpe.chain == chain)].sn1
                           .replace([np.inf, -np.inf], np.nan).dropna().values) for c in disp]
        tk = astat.tukey(groups, disp)
        sig[("hom", chain)] = dict(av=astat.anova(groups), tk=tk)
        srows = []                              # star = differs from IMMREP25 (Tukey HSD, p<0.05)
        for c in disp:
            r = hom[(hom.cohort == c) & (hom.chain == chain) & (hom.d == 1)].iloc[0]
            if astat.star_vs(tk, c, "immrep25_pos"):
                srows.append({"x": COLIDX[c], "y": float(r.hi) * 1.4, "lab": "*"})
        _write_dat(pd.DataFrame(srows, columns=["x", "y", "lab"]), f"homology_sig_TR{chain}.dat")
    disp_pair = [c for c in DISP_PAIR if c in set(pair.cohort)]
    # every displayed series gets its own ANOVA and its own Tukey-vs-IMMREP25 test, so the two
    # gene-usage reference series are held to the same standard as the inter-chain MI
    for col, key in (("gene_excess", "gene"), ("gene_excess_a", "geneA"),
                     ("gene_excess_b", "geneB"), ("mi_excess", "mi")):
        groups = [ppe[ppe.cohort == c][col].dropna().values for c in disp_pair]
        sig[("pair", key)] = dict(av=astat.anova(groups), tk=astat.tukey(groups, disp_pair))
    # x offsets must match the grouped-bar offsets in fig_pairing.gp
    srows = []
    for key, hi_col, dx in (("geneA", "geneA_hi", -0.25), ("geneB", "geneB_hi", 0.0),
                            ("mi", "mi_hi", 0.25)):
        for c in disp_pair:
            r = pair[pair.cohort == c].iloc[0]
            if astat.star_vs(sig[("pair", key)]["tk"], c, "immrep25_pos"):
                srows.append({"x": COLIDX[c] + dx, "y": float(r[hi_col]) + 0.10, "lab": "*"})
    _write_dat(pd.DataFrame(srows, columns=["x", "y", "lab"]), "pairing_sig.dat")

    m = {
        "immHomA": H("immrep25_pos", "A"), "immHomB": H("immrep25_pos", "B"),
        "iiHomA": H("immrep22_true", "A"), "iiHomB": H("immrep22_true", "B"),
        "hqHomB": H("vdjdb_hq", "B"), "trueHomB": H("tcrvdb_true", "B"), "lqHomB": H("vdjdb_lq", "B"),
        "falseHomB": H("tcrvdb_false", "B"),
        "olgaRHomB": H("olga_random", "B"), "olgaRHomA": H("olga_random", "A"),
        "airrHomB": H("airr_control", "B"), "airrHomA": H("airr_control", "A"),
        "psHomB": H("pairseq_mock", "B"), "psHomA": H("pairseq_mock", "A"),
        "psGene": P("pairseq_mock", "gene_mean"), "psMi": P("pairseq_mock", "mi_mean"),
        "mlrHomB": H("mlr_prolif", "B"),
        "immGene": P("immrep25_pos", "gene_mean"), "immMi": P("immrep25_pos", "mi_mean"),
        "immGeneA": P("immrep25_pos", "geneA_mean"), "immGeneB": P("immrep25_pos", "geneB_mean"),
        "iiGene": P("immrep22_true", "gene_mean"), "iiMi": P("immrep22_true", "mi_mean"),
        "hqGene": P("vdjdb_hq", "gene_mean"), "trueMi": P("tcrvdb_true", "mi_mean"),
        "olgaRGene": P("olga_random", "gene_mean"), "olgaRMi": P("olga_random", "mi_mean"),
        # within_frac is NOT chance-corrected (chance = 1/n_epitopes), so it is comparable only
        # between cohorts carrying the same number of epitopes. immWithin vs psWithin is such a
        # pair (20 each) and is the one quoted; iiWithin (7 epitopes) and hqWithin (83) are
        # emitted for the record and not compared across the ladder -- see SOURCES.
        "iiWithin": GW("immrep22_true"), "immWithin": GW("immrep25_pos"), "hqWithin": GW("vdjdb_hq"),
        "psWithin": GW("pairseq_mock"),
        "pubAny": 100 * float(pub_summary.frac_public_any.iloc[0]),
        "pubA": 100 * float(pub_summary.frac_public_a.iloc[0]),
        "pubB": 100 * float(pub_summary.frac_public_b.iloc[0]),
        "npHomA": float(pub[(pub.subset == "non_public") & (pub.chain == "A")].sn.iloc[0]),
        "npHomB": float(pub[(pub.subset == "non_public") & (pub.chain == "B")].sn.iloc[0]),
        # CIs, so the manuscript can state intervals rather than bare point estimates
        "immHomBLo": HC("immrep25_pos", "B", "lo"), "immHomBHi": HC("immrep25_pos", "B", "hi"),
        "immHomALo": HC("immrep25_pos", "A", "lo"), "immHomAHi": HC("immrep25_pos", "A", "hi"),
        "npHomALo": float(pub[(pub.subset == "non_public") & (pub.chain == "A")].lo.iloc[0]),
        "npHomAHi": float(pub[(pub.subset == "non_public") & (pub.chain == "A")].hi.iloc[0]),
        "immMiLo": P("immrep25_pos", "mi_lo"), "immMiHi": P("immrep25_pos", "mi_hi"),
        "psMiLo": P("pairseq_mock", "mi_lo"), "psMiHi": P("pairseq_mock", "mi_hi"),
        # publicity contrast on the inter-chain probe (all vs novel, floor 10; mock for reference)
        "npMi": PM("non_public", "mi_excess"), "npMiLo": PM("non_public", "lo"),
        "npMiHi": PM("non_public", "hi"),
        "immMiPub": PM("all", "mi_excess"), "immMiPubLo": PM("all", "lo"),
        "immMiPubHi": PM("all", "hi"),
        "psMiPub": PM("pairseq_mock", "mi_excess"), "psMiPubLo": PM("pairseq_mock", "lo"),
        "psMiPubHi": PM("pairseq_mock", "hi"),
    }
    ints = {"immWithinB": imm_within[0], "immWithinA": imm_within[1],
            "olgaWithinB": imm_within[2], "olgaWithinA": imm_within[3],
            "psWithinB": int(per_ep[("pairseq_mock", "B")].m1.sum()) if ("pairseq_mock", "B") in per_ep else 0,
            "psNep": NEP("pairseq_mock"),
            "iiNep": NEP("immrep22_true"), "immNep": NEP("immrep25_pos"),
            "npN": int(pub[(pub.subset == "non_public") & (pub.chain == "B")].n.iloc[0]),
            "npEdgesB": int(pub[(pub.subset == "non_public") & (pub.chain == "B")].within_pairs.iloc[0]),
            "npEdgesA": int(pub[(pub.subset == "non_public") & (pub.chain == "A")].within_pairs.iloc[0]),
            "npNepB": int(pub[(pub.subset == "non_public") & (pub.chain == "B")].n_ep.iloc[0]),
            "npMiNep": int(pub_mi[pub_mi.subset == "non_public"].n_ep.iloc[0])}
    def fmt(v):
        if not np.isfinite(v):
            return "n/a"
        a = abs(v)
        if a >= 100:
            s = "%.0f" % v
        elif a >= 10:
            s = "%.1f" % v
        elif a >= 1:
            s = "%.2f" % v
        else:
            s = "%.3f" % v
        # a value that rounds to zero must not be printed as "-0.000"
        return s.lstrip("-") if float(s) == 0 else s
    # string macros: ANOVA F, p-values (each carries its own relational op for $p...$), medians
    def _tkp(tk, a, b):
        return astat.fmt_p(tk.get((a, b), tk.get((b, a), float("nan"))))
    strmac = {}
    for chain in ("B", "A"):
        s = sig[("hom", chain)]
        strmac["homAnovaF" + chain] = fmt(s["av"]["F"])
        strmac["homAnovaP" + chain] = astat.fmt_p(s["av"]["p"])
    strmac["pImmvsMlrB"] = _tkp(sig[("hom", "B")]["tk"], "immrep25_pos", "mlr_prolif")
    strmac["geneAnovaF"] = fmt(sig[("pair", "gene")]["av"]["F"])
    strmac["geneAnovaP"] = astat.fmt_p(sig[("pair", "gene")]["av"]["p"])
    strmac["miAnovaF"] = fmt(sig[("pair", "mi")]["av"]["F"])
    strmac["miAnovaP"] = astat.fmt_p(sig[("pair", "mi")]["av"]["p"])
    with open(os.path.join(ADAT, "audit_macros.tex"), "w") as fh:
        for k, v in m.items():
            fh.write("\\newcommand{\\%s}{%s}\n" % (k, fmt(v)))
        for k, v in ints.items():
            fh.write("\\newcommand{\\%s}{%d}\n" % (k, v))
        for k, v in strmac.items():
            fh.write("\\newcommand{\\%s}{%s}\n" % (k, v))
    print("\nDone -> results/ and appendix/analysis/*.dat (+ macros, tables)")


if __name__ == "__main__":
    run()
