#!/usr/bin/env python
# 2026-08-09  Supplementary Table S8: the size of every audited cohort.
#
# Two figure captions previously pointed at per-cohort n that was never typeset anywhere (it lived
# only in results/counts.csv). This emits it as a table: total records and unique CDR3 clonotypes
# per chain, the number of epitope labels, and how many of those clear the >=30-records-per-chain
# floor that every one-vs-many probe applies. Counts are exact integers, never pooled or rounded.
#   Run: python src/cohort_counts.py
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
COUNTS = REPO / "results" / "counts.csv"
HOM = REPO / "results" / "homology_sn.csv"
OUT = REPO.parent / "2026-immrep25-audit-ms" / "tables" / "cohort_counts_table.tex"

# display order = the calibration ladder of Table 1, controls last
ORDER = ["tcrvdb_true", "vdjdb_hq", "immrep22_true", "vdjdb_lq", "tcrvdb_false", "immrep25_pos",
         "pairseq_mock", "mlr_prolif", "airr_control", "olga_random"]
LAB = {"tcrvdb_true": r"TCRvdb$^{(+)}$", "vdjdb_hq": r"VDJdb$^{(HQ)}$",
       "immrep22_true": r"IMMREP22$^{(+)}$", "vdjdb_lq": r"VDJdb$^{(LQ)}$",
       "tcrvdb_false": r"TCRvdb$^{(-)}$", "immrep25_pos": r"IMMREP25$^{(+)}$",
       "pairseq_mock": "pairSEQ mock", "mlr_prolif": r"MLR expanded ($\beta$)",
       "airr_control": "AIRR random", "olga_random": "OLGA random"}


def main():
    c = pd.read_csv(COUNTS).set_index("cohort")
    # qualifying epitopes per chain: the n_ep the homology probe actually scored at d=1
    q = (pd.read_csv(HOM).query("d == 1").pivot_table(index="cohort", columns="chain",
                                                      values="n_ep", aggfunc="max"))
    rows = []
    for k in ORDER:
        n = c.loc[k]
        qa, qb = (q.loc[k].get(ch) for ch in ("A", "B"))
        f = lambda v: "--" if v is None or pd.isna(v) or v == 0 else f"{int(v):,}"
        rows.append(" & ".join([LAB[k], f(n.n_paired), f(n.n_chainA), f(n.n_chainB),
                                f(n.n_epitopes), f(qa), f(qb)]) + r" \\")
    body = "\n".join(rows[:6] + [r"\midrule"] + rows[6:])
    OUT.write_text(r"""%% GENERATED by src/cohort_counts.py -- do not edit.
%% Regenerate: python src/cohort_counts.py (from the 2026-immrep25-audit repo).
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
 & paired & \multicolumn{2}{c}{unique CDR3} & &
 \multicolumn{2}{c}{qualifying epitopes} \\
\cmidrule(lr){3-4}\cmidrule(lr){6-7}
cohort & records & TCR$\alpha$ & TCR$\beta$ & epitopes & TCR$\alpha$ & TCR$\beta$ \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
""")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
