"""Per-epitope table for the 20 IMMREP25 peptides: presentation (NetMHCpan-4.2) x TCR convergence.
# 2026-08-06

Answers the "intrinsic hardness / flat epitope" alternative (reviewer m10): are the labelled
peptides even presented, and does any single epitope escape the CDR3-convergence floor? For each
peptide we join its HLA restriction and NetMHCpan-4.2 eluted-ligand %Rank / affinity / binding level
(is it a genuine presented epitope?) to its per-epitope homology S/N (does its TCRs converge?).

NetMHCpan-4.2 is expected at $NETMHCPAN (default the academy-software install); if absent, the
script reuses the committed results/immrep25_peptides.csv so the table still builds.

Usage: uv run python src/peptide_table.py   # writes results/immrep25_peptides.csv + table + macros
"""
from __future__ import annotations
import os, subprocess, tempfile
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(REPO, "results")
ADAT = os.path.join(REPO, "appendix", "analysis")
TABLES = os.path.join(os.path.dirname(REPO), "2026-immrep25-audit-ms", "tables")
NMP = os.environ.get("NETMHCPAN",
                     "/Users/mikesh/work/academy/software/netMHCpan-4.2/netMHCpan")


def _allele(hla: str) -> str:               # "A*02:01" -> "HLA-A02:01"
    return "HLA-" + hla.replace("*", "")


def _run_netmhcpan(peptides, allele) -> pd.DataFrame:
    with tempfile.NamedTemporaryFile("w", suffix=".pep", delete=False) as fh:
        fh.write("\n".join(peptides) + "\n"); path = fh.name
    out = subprocess.run([NMP, "-p", "-a", allele, "-BA", path],
                         capture_output=True, text=True).stdout
    os.unlink(path)
    rows = []
    for ln in out.splitlines():
        f = ln.split()
        if len(f) >= 16 and f[0].isdigit() and f[1].startswith("HLA-"):
            band = f[17] if len(f) >= 18 else "NB"     # SB / WB / (none)->NB
            rows.append({"peptide": f[2], "rank_el": float(f[12]),
                         "aff_nm": float(f[15]), "bind": band})
    return pd.DataFrame(rows)


def presentation(pep2hla: dict) -> pd.DataFrame:
    try:
        parts = []
        for allele in sorted(set(pep2hla.values())):
            peps = [p for p, h in pep2hla.items() if h == allele]
            parts.append(_run_netmhcpan(peps, _allele(allele)))
        df = pd.concat(parts, ignore_index=True)
        if len(df) == len(pep2hla):
            return df
        raise RuntimeError("NetMHCpan returned %d/%d rows" % (len(df), len(pep2hla)))
    except (FileNotFoundError, RuntimeError) as e:
        cache = os.path.join(RESULTS, "immrep25_peptides.csv")
        print("NetMHCpan unavailable (%s); reusing %s" % (e, cache))
        return pd.read_csv(cache)[["peptide", "rank_el", "aff_nm", "bind"]]


def run():
    d = pd.read_csv(os.path.join(REPO, "dump", "immrep25",
                                 "immrep2025_for_release.tsv"), sep="\t")
    pos = d[d.label == 1]
    meta = pos.groupby("peptide").agg(hla=("hla", "first"), n=("peptide", "size")).reset_index()
    pep2hla = dict(zip(meta.peptide, meta.hla))
    pres = presentation(pep2hla)

    hp = pd.read_csv(os.path.join(RESULTS, "homology_per_epitope.csv"))
    hp = hp[hp.cohort == "immrep25_pos"]
    snb = hp[hp.chain == "B"].set_index("epitope").sn1
    sna = hp[hp.chain == "A"].set_index("epitope").sn1

    t = meta.merge(pres, on="peptide", how="left")
    t["sn_b"] = t.peptide.map(snb); t["sn_a"] = t.peptide.map(sna)
    t = t.sort_values("sn_b", ascending=False).reset_index(drop=True)
    t.to_csv(os.path.join(RESULTS, "immrep25_peptides.csv"), index=False)

    # LaTeX table
    def _band(b):
        return {"SB": "strong", "WB": "weak"}.get(b, "non")
    with open(os.path.join(TABLES, "immrep25_peptide_table.tex"), "w") as fh:
        fh.write("%% GENERATED by src/peptide_table.py -- do not edit.\n"
                 "%% Regenerate: python src/peptide_table.py (from the 2026-immrep25-audit repo).\n")
        fh.write("\\begin{tabular}{llrrrrr}\n\\toprule\n")
        fh.write("peptide & HLA & $n$ & S/N $\\beta$ & S/N $\\alpha$ & "
                 "\\%Rank$_{\\mathrm{EL}}$ & presentation \\\\\n\\midrule\n")
        for _, r in t.iterrows():
            fh.write("\\texttt{%s} & %s & %d & %.2f & %.2f & %.2f & %s \\\\\n"
                     % (r.peptide, r.hla, r.n, r.sn_b, r.sn_a, r.rank_el, _band(r.bind)))
        fh.write("\\bottomrule\n\\end{tabular}\n")

    # summary macros
    nsb = int((t.bind == "SB").sum()); nwb = int((t.bind == "WB").sum())
    macros = {
        "pepNstrong": "%d" % nsb, "pepNweak": "%d" % nwb,
        "pepNpresented": "%d" % (nsb + nwb), "pepTotal": "%d" % len(t),
        "pepMedRank": "%.2f" % t.rank_el.median(),
        "pepNhla": "%d" % t.hla.nunique(),
        "pepHlaList": ", ".join(sorted(t.hla.unique())),
        "pepNabove": "%d" % int((t.sn_b > 2).sum()),         # epitopes above a 2x floor on beta
        "pepMaxSnb": "%.1f" % t.sn_b.max(),
        "pepMaxSnbEp": "\\texttt{%s}" % t.loc[t.sn_b.idxmax(), "peptide"],
    }
    with open(os.path.join(ADAT, "immrep25_peptide_macros.tex"), "w") as fh:
        for k, v in macros.items():
            fh.write("\\newcommand{\\%s}{%s}\n" % (k, v))
    print(t[["peptide", "hla", "sn_b", "sn_a", "rank_el", "bind"]].to_string(index=False))
    print("\n%d/%d presented (%d strong, %d weak); median %%Rank_EL %.2f; %d epitopes S/N_beta>2"
          % (nsb + nwb, len(t), nsb, nwb, t.rank_el.median(), int((t.sn_b > 2).sum())))
    print("wrote results/immrep25_peptides.csv + immrep25_peptide_table.tex + macros")


if __name__ == "__main__":
    run()
