"""The parameter table for the ESM-based representation probes, read out of the code itself.
# 2026-08-09

Every knob of the three REPORTED representation probes (Leiden clustering, kNN mutual information,
held-out learning) is imported from the module that defines it and written to a supplementary table,
so the reported settings cannot drift from the settings actually used. esm_signal.py's neighbour
purity statistic runs on the same subsample and shares K_NN, but nothing in the manuscript reports
it, so it is not listed here.

Usage: python src/probe_params.py    # writes ../2026-immrep25-audit-ms/tables/probe_params_table.tex
"""
from __future__ import annotations
import os
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "src"))
import esm_signal as es       # noqa: E402
import esm_cluster as ec      # noqa: E402
import degenerate as dg       # noqa: E402
import mi_master as mm        # noqa: E402

TABLES = os.path.join(os.path.dirname(REPO), "2026-immrep25-audit-ms", "tables")
ADAT = os.path.join(REPO, "appendix", "analysis")


def _global_pca():
    """Per chain: clonotypes the global PCA was fit on, and the variance its components keep."""
    out = {}
    for ch in ("A", "B"):
        p = np.load(os.path.join(es.CACHE, "pca_%s.npz" % ch))
        out[ch] = (int(p["n"]), 100.0 * p["evr"].sum())
    return out


def run():
    gp = _global_pca()

    # (parameter, value, what it controls, which probes use it)
    rows = [
        (r"ESM-2 checkpoint", r"\texttt{esm2\_t12\_35M\_UR50D}",
         "mean-pooled residue embedding (480-d)", "all three"),
        (r"$n_{\min}$ per epitope", "%d" % es.MIN_N,
         "an epitope qualifies for the probe", "all three"),
        (r"receptors per epitope", "%d" % es.PER_EPI,
         "equalises epitope weights in a cohort", "all three"),
        (r"epitopes per cohort", "all qualifying",
         "no cap on epitopes above $n_{\\min}$", "all three"),
        (r"$k$ (neighbour graph)", "%d" % es.K_NN,
         "neighbourhood size, cosine metric", "Leiden"),
        (r"Leiden resolution", "%.1f" % ec.RES,
         "RBConfiguration granularity", "Leiden"),
        (r"PCA dimension", "%d" % es.PCA_DIM,
         "one projection per chain, all clonotypes", r"$k$-NN MI"),
        (r"$k$ (MI estimator)", "%d" % mm.KSG_K,
         "Ross (2014) neighbour count", r"$k$-NN MI"),
        (r"classifier", r"multinomial logistic, $C=1$",
         "the held-out epitope probe", "held-out"),
        (r"cross-validation", r"%d-fold $\times$ %d repeats" % (dg.N_REPEATS, dg.N_CVREP),
         "grouped on CDR3; sd across repeats", "held-out"),
        (r"$n_{\min}$ per epitope (probe)", "%d" % dg.MIN_PER,
         "an epitope enters the held-out fit", "held-out"),
        (r"bootstrap resamples", "%d" % ec.N_BOOT,
         "CIs on ARI/AMI", "Leiden"),
        (r"permutations", "%d" % ec.N_PERM, "label-shuffle null for MI in bits", "Leiden"),
        (r"permutations", "%d" % dg.N_PERM, "label-shuffle null for MI in bits", "held-out"),
        (r"permutations", "%d" % mm.N_PERM, "label-shuffle null for MI in bits", r"$k$-NN MI"),
    ]
    with open(os.path.join(TABLES, "probe_params_table.tex"), "w") as fh:
        fh.write("%% GENERATED by src/probe_params.py -- do not edit.\n"
                 "%% Regenerate: python src/probe_params.py (from the 2026-immrep25-audit repo).\n")
        # tabularx with the role column as X: the role strings are long enough that a plain
        # tabular ran ~115 pt off the page and clipped the "probes" column entirely.
        fh.write("\\begin{tabularx}{\\linewidth}"
                 "{@{}l l >{\\raggedright\\arraybackslash}X l@{}}\n\\toprule\n"
                 "parameter & value & role & probes \\\\\n\\midrule\n")
        for r in rows:
            fh.write(" & ".join(r) + " \\\\\n")
        fh.write("\\bottomrule\n\\end{tabularx}\n")
    with open(os.path.join(ADAT, "probe_params_macros.tex"), "w") as fh:
        for ch in ("A", "B"):
            fh.write("\\newcommand{\\allseq%s}{%s}\n" % (ch, "{:,}".format(gp[ch][0])))
            fh.write("\\newcommand{\\evr%s}{%.0f}\n" % (ch, gp[ch][1]))
    print("wrote tables/probe_params_table.tex + probe_params_macros.tex")
    for r in rows:
        print("  %-30s %s" % (r[0], r[1]))


if __name__ == "__main__":
    run()
